### ISSUE TITLE
卡在了最后一步，一直在初始化

### ISSUE THREAD

**Issue by data7799** [yllhwa/RSSWorker#1]
前面部署过程都很顺利，直到最后出现这个界面，刷新后页面不变，仍然显示初始化中，等了很久还是一样：
![image](https://github.com/yllhwa/RSSWorker/assets/15697784/e65130a5-cd9e-40bb-9bb3-587b51260d02)

**Comment by yllhwa** [comment]
clone下来直接npm install，npm run deploy试试呢

**Comment by data7799** [comment]
试了下，本地部署是成功的，尝试了拼接订阅源，把订阅源在浏览器打开，也能正常抓取内容
![image](https://github.com/yllhwa/RSSWorker/assets/15697784/4431eada-51ee-4990-aef1-4ae88295add4)
