### ISSUE TITLE
小红书订阅源没有pubDate

### ISSUE THREAD

**Issue by JerryYang-30** [yllhwa/RSSWorker#13]
图1为小红书订阅源，图2为Bilibili订阅源。可以看见，小红书订阅源爬取的XML没有笔记的发布日期pubDate，这导致订阅小红书源时，没有按照顺序推送历史笔记。我不懂编程，不知道该如何添加pubDate……
小红书源：`/rss/xiaohongshu/user/5efdeba4000000000101e7e6`
Bilibili源（有时可能失效，疑似跟爬取频率有关）：`/rss/bilibili/user/dynamic/1405395281`
![RSS爬取的小红书XML格式](https://github.com/yllhwa/RSSWorker/assets/102589310/dfa18b93-6a09-4a64-ba28-ab2b3b73693c)
![RSS爬取的B站XML格式](https://github.com/yllhwa/RSSWorker/assets/102589310/16e296e2-5268-4074-bc98-65588612f11b)

**Comment by yllhwa** [comment]
小红书信息源未提供日期，所以无法提取pubDate。
至于B站，降低爬取频率会改善报错情况。

**Comment by JerryYang-30** [comment]
> 小红书信息源未提供日期，所以无法提取pubDate。 至于B站，降低爬取频率会改善报错情况。

如何降低爬取频率啊，我用的QiReader，貌似没有调整读取文章频率的按钮……

**Comment by yllhwa** [comment]
有空我会尝试加一个从网页接口爬取的订阅链接，可以解决报错问题，不过可能遇到反爬。

目前采用的grpc接口原本是为了绕过反爬，不过受限于cloudflare的能力，连续多次请求的时候容易报错。

**Comment by JerryYang-30** [comment]
> 有空我会尝试加一个从网页接口爬取的订阅链接，可以解决报错问题，不过可能遇到反爬。
> 
> 目前采用的grpc接口原本是为了绕过反爬，不过受限于cloudflare的能力，连续多次请求的时候容易报错。

谢谢作者大大😭
