### ISSUE TITLE
某微博订阅源返回500

### ISSUE THREAD

**Issue by JerryYang-30** [yllhwa/RSSWorker#16]
原微博地址：https://weibo.com/u/7045535355
RSS源地址：https://rss-worker.jerry30yang.workers.dev/rss/weibo/user/7045535355
订阅了30多个微博源，都没问题，目前只有上面这个遇到问题

报错如下：
RSSWorker - Made with ❤
500 - Internal Server Error

debug message: TypeError: Cannot read properties of undefined (reading 'url')

stack:
TypeError: Cannot read properties of undefined (reading 'url')
at worker.js:2008:86
at Array.forEach ()
at Object.formatExtended (worker.js:2007:16)
at worker.js:21123:51
at async Promise.all (index 7)
at async deal4 (worker.js:21103:21)
at async dispatch (worker.js:3737:17)
at async worker.js:4246:25

See [GitHub](https://github.com/yllhwa/RSSWorker) for more information.

![bani0q42 14a](https://github.com/user-attachments/assets/b7e96a53-c925-43a7-adb1-911b6aae5461)

**Comment by yllhwa** [comment]
fixed
