### ISSUE TITLE
telegram报错Encoding error

### ISSUE THREAD

**Issue by jbao-825** [yllhwa/RSSWorker#20]
This page contains the following errors:
error on line 97 at column 25: Encoding error
Below is a rendering of the page up to the first error.

好像只有这个telegram频道会报错，其他都没问题。

![image](https://github.com/user-attachments/assets/4724bba8-04cb-4b0d-972c-1522af0fd42b)

**Comment by yllhwa** [comment]
fixed
不过这个应该不影响订阅？
