### ISSUE TITLE
请问在Worker部署完之后，访问网址报错404是什么原因

### ISSUE THREAD

**Issue by torinkan** [yllhwa/RSSWorker#3]
![image](https://github.com/yllhwa/RSSWorker/assets/13595721/3787c8e1-e795-406e-8bb7-2243b41c1e5d)

**Comment by yllhwa** [comment]
未复现

![image](https://github.com/yllhwa/RSSWorker/assets/42028599/35c2de73-c9ad-4cd4-ab2c-e59b5dab7df0)

**Comment by torinkan** [comment]
@yllhwa  另外我尝试使用Readme里面的Deploy to Cloudflare Workers, 但是最后部署失败。请问如何排查？谢谢！
我发现Action里面的flow压根都没有运行。
![image](https://github.com/yllhwa/RSSWorker/assets/13595721/a22fb832-9bf0-495e-89ae-ab984da3cd3e)

**Comment by yllhwa** [comment]
> @yllhwa 另外我尝试使用Readme里面的Deploy to Cloudflare Workers, 但是最后部署失败。请问如何排查？谢谢！ 我发现Action里面的flow压根都没有运行。 ![image](https://user-images.githubusercontent.com/13595721/278927564-a22fb832-9bf0-495e-89ae-ab984da3cd3e.png)

创建过程中需要填写cloudflare凭据，注意填写是否正确。

另外之前解决了这个问题，如果你是用的旧仓库需要同步下最新的试试。

**Comment by torinkan** [comment]
> > @yllhwa 另外我尝试使用Readme里面的Deploy to Cloudflare Workers, 但是最后部署失败。请问如何排查？谢谢！ 我发现Action里面的flow压根都没有运行。 ![image](https://user-images.githubusercontent.com/13595721/278927564-a22fb832-9bf0-495e-89ae-ab984da3cd3e.png)
> 
> 创建过程中需要填写cloudflare凭据，注意填写是否正确。
> 
> 另外之前解决了这个问题，如果你是用的旧仓库需要同步下最新的试试。

我确认Account ID和Token是对的，如果不对的话，会在部署之前就会报错。我想请问一下，针对账号的权限有什么要去吗？以下是我的配置，帮忙看下是否正确？
![image](https://github.com/yllhwa/RSSWorker/assets/13595721/72775614-2ce5-4e28-b81f-cab2b6bb31ab)

**Comment by yllhwa** [comment]
我的权限长这样，看起来没问题
![image](https://github.com/yllhwa/RSSWorker/assets/42028599/53dd5a58-b708-4489-9257-260fe495b4b4)
