### ISSUE TITLE
deploy到Cloudflare后无法使用

### ISSUE THREAD

**Issue by nageshuizeii** [yllhwa/RSSWorker#5]
![CleanShot 2023-11-10 at 10 48 59@2x](https://github.com/yllhwa/RSSWorker/assets/16527235/de08d616-a1f6-4e8e-b3e8-fee55c4a252c)
![CleanShot 2023-11-10 at 10 49 14@2x](https://github.com/yllhwa/RSSWorker/assets/16527235/c6bdd360-42a3-425d-ab1f-7e97c49c0555)
请问博客有文章教程吗

**Comment by yllhwa** [comment]
在这里手动 run 一下试试呢。
![image](https://github.com/yllhwa/RSSWorker/assets/42028599/f3455baa-d04c-4c6f-a172-cc620243aee4)

**Comment by nageshuizeii** [comment]
谢谢回复，按您说的试了一下，应该是 fork 之后没有出现您图里的 5 Workflow 导致的，我是空白的
![CleanShot 2023-11-15 at 11 11 27@2x](https://github.com/yllhwa/RSSWorker/assets/16527235/afa61001-df30-4cf8-97fe-f67788ed7077)
![CleanShot 2023-11-15 at 11 12 53@2x](https://github.com/yllhwa/RSSWorker/assets/16527235/a6dce9ad-f94f-47f3-86a2-1c50947ede9a)
