### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by Sostay** [yllhwa/RSSWorker#6]
之前还是正常的，今天突然访问不了

debug message: TypeError: Cannot read properties of undefined (reading 'slice')

stack:
TypeError: Cannot read properties of undefined (reading 'slice')
at getUser (worker.js:20997:19)
at async deal4 (worker.js:21010:7)
at async worker.js:4087:62

![image](https://github.com/yllhwa/RSSWorker/assets/6897274/ce7ca64f-d590-4699-a37d-a63681812374)
![image](https://github.com/yllhwa/RSSWorker/assets/6897274/5100db0b-0f46-40ab-91ef-d6dcfd86eae7)

**Comment by yllhwa** [comment]
已修复，需要重新部署并修改订阅链接。
> 小红书更新后不能再使用小红书号，需要使用小红书用户ID。  
> 获取方法：  
> 移动端：用户页面 > 右上角三个点 > 复制链接 > 获取链接中的用户ID  
> 网页端：用户页面 > 链接中的用户ID  
> 格式：https://www.xiaohongshu.com/user/profile/5d2aec020000000012037401
