### ISSUE TITLE
小红书的订阅是不是失效了？

### ISSUE THREAD

**Issue by xlxyq** [yllhwa/RSSWorker#7]
![image](https://github.com/yllhwa/RSSWorker/assets/32615715/fcdd8344-b902-4322-9411-9610ecc56656)
自己测试了很多个小红书账户，都无法订阅。

**Comment by xlxyq** [comment]
测试了其他三个订阅，都是正常的，唯独小红书不行。

**Comment by yllhwa** [comment]
已修复，需要修改订阅链接。
> 小红书更新后不能再使用小红书号，需要使用小红书用户ID。  
> 获取方法：  
> 移动端：用户页面 > 右上角三个点 > 复制链接 > 获取链接中的用户ID  
> 网页端：用户页面 > 链接中的用户ID  
> 格式：https://www.xiaohongshu.com/user/profile/5d2aec020000000012037401

**Comment by xlxyq** [comment]
![image](https://github.com/yllhwa/RSSWorker/assets/32615715/33ecd2e7-69c3-4d6d-b575-629f4a4e296c)
</br>
![image](https://github.com/yllhwa/RSSWorker/assets/32615715/356e8174-7071-4f79-8485-e6afdd3d21e6)

我用了你介绍页提供的小红书链接的用户id，也测试了小红书号，但是两个测试都失败了。

**Comment by yllhwa** [comment]
代码有更新，需要重新部署

**Comment by xlxyq** [comment]
感谢，已解决。
