### ISSUE TITLE
是否可以增加一个路由来只显示UP主的视频

### ISSUE THREAD

**Issue by MoeSakuraa** [yllhwa/RSSWorker#8]
类似 RSSHub 一样增加一个`/rss/bilibili/user/video/`路由，只显示UP主的视频，因为有些UP主的动态发得太频繁了，有时只想看他们的视频

**Comment by yllhwa** [comment]
我手机root掉了，没法抓包b站视频页的grpc是哪个（

**Comment by MoeSakuraa** [comment]
在`/rss/bilibili/user/video/dynamic/` 中，`<category>`是`av`的就是视频，或许能直接过滤？

**Comment by yllhwa** [comment]
已添加
